// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5svTcRBdHYlNvTeFf3eN_S7zR1H7Ymps',
    appId: '1:767793565429:web:7bcc435dae2f879d22bfbc',
    messagingSenderId: '767793565429',
    projectId: 'chuiter',
    authDomain: 'chuiter.firebaseapp.com',
    storageBucket: 'chuiter.appspot.com',
    measurementId: 'G-2MZKWD06VD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQamErF3pk1zObw5fZX_p-03WY7uRs4zM',
    appId: '1:767793565429:android:6720bec2eec5ae3022bfbc',
    messagingSenderId: '767793565429',
    projectId: 'chuiter',
    storageBucket: 'chuiter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj3idlFboDq1SFDKjT3cYgjRiYLDWiERM',
    appId: '1:767793565429:ios:0be98b9faaad4dc622bfbc',
    messagingSenderId: '767793565429',
    projectId: 'chuiter',
    storageBucket: 'chuiter.appspot.com',
    androidClientId: '767793565429-36to3istgcvk43nqk4rvf331pdet2r37.apps.googleusercontent.com',
    iosClientId: '767793565429-5o9c5apg8f9qqjikhmepsov1b955k9c9.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj3idlFboDq1SFDKjT3cYgjRiYLDWiERM',
    appId: '1:767793565429:ios:0be98b9faaad4dc622bfbc',
    messagingSenderId: '767793565429',
    projectId: 'chuiter',
    storageBucket: 'chuiter.appspot.com',
    androidClientId: '767793565429-36to3istgcvk43nqk4rvf331pdet2r37.apps.googleusercontent.com',
    iosClientId: '767793565429-5o9c5apg8f9qqjikhmepsov1b955k9c9.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitter',
  );
}
